import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Document, { Html, Head, Main, NextScript } from "next/document";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<head>
				<link
					rel="stylesheet"
					href="https://use.typekit.net/heo3ekj.css"
				/>
			</head>
			<body className={inter.className}>{children}</body>
		</html>
	);
}
